const Incident = require("../models/Incident");
exports.getAllIncidents = async (req, res) => {
    try {
        const incidents = await Incident.find();
        res.status(200).json(incidents);
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
};

exports.getIncidentById = async (req, res) => {
    try {
        const incident = await Incident.findById(req.params.id);
        if (!incident) {
            return res.status(404).json({ message: 'Incident not found' });
        }
        res.status(200).json(incident);
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
};

exports.createIncident = async (req, res) => {
    try {
        const incident = new Incident(req.body);
        await incident.save();
        res.status(201).json(incident);
    } catch (error) {
        res.status(400).json({ error: error.message });
    }
};

exports.updateIncident = async (req, res) => {
    try {
        const incident = await Incident.findByIdAndUpdate(req.params.id, req.body, { new: true, runValidators: true });
        if (!incident) {
            return res.status(404).json({ message: 'Incident not found' });
        }
        res.status(200).json(incident);
    } catch (error) {
        res.status(400).json({ error: error.message });
    }
};

exports.deleteIncident = async (req, res) => {
    try {
        const incident = await Incident.findByIdAndDelete(req.params.id);
        if (!incident) {
            return res.status(404).json({ message: 'Incident not found' });
        }
        res.status(200).json({ message: 'Incident deleted successfully' });
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
};